/*******************************************************************************
功能    : .c对应的inc文件
创建人  : 唐春平
创建日期: 200.01.10
修改记录:
*******************************************************************************/
extern BOOL    g_bSipSyntaxInit;
extern UCHAR  *g_pucSipSyntaxBuffer;
extern UCHAR   g_ucSipRuleListIndex;
extern SYNTAX_APP_RULE_S g_astSipAppRuleTbl[SIP_ABNF_RULE_BUTT];
extern SIP_SYNTAX_HEADER_MAP_S g_astSipSyntaxHeaderTbl[SIP_HEADER_BUTT];