typedef enum tagDIAMETER_COMMAND_E
{
    DIAMETER_COMMAND_UAR,
    DIAMETER_COMMAND_UAA,
    DIAMETER_COMMAND_SAR,
    DIAMETER_COMMAND_SAA,
    DIAMETER_COMMAND_LIR,
    DIAMETER_COMMAND_LIA,
    DIAMETER_COMMAND_MAR,
    DIAMETER_COMMAND_MAA,
    DIAMETER_COMMAND_RTR,
    DIAMETER_COMMAND_RTA,
    DIAMETER_COMMAND_PPR,
    DIAMETER_COMMAND_PPA,
    DIAMETER_COMMAND_BUTT
}DIAMETER_COMMAND_E;

typedef enum tagDIAMETER_AVP_E
{
    DIAMETER_AVP_USER_NAME,
    DIAMETER_AVP_SIP_VNI,
    DIAMETER_AVP_SIP_AOR,
    DIAMETER_AVP_SIP_AUTH,
    DIAMETER_AVP_SIP_AUTH_INFO,
    DIAMETER_AVP_BUTT
}DIAMETER_AVP_E;