/* 事务层定时器 */
typedef enum tagSIP_TXN_TIMER_NAME_E
{
    SIP_TXN_TIMER_A,
    SIP_TXN_TIMER_B,
    SIP_TXN_TIMER_D,
    SIP_TXN_TIMER_E,
    SIP_TXN_TIMER_F,
    SIP_TXN_TIMER_K,
    SIP_TXN_TIMER_G,
    SIP_TXN_TIMER_H,
    SIP_TXN_TIMER_I,
    SIP_TXN_TIMER_J,
    SIP_TXN_TIMER_BUTT
}SIP_TXN_TIMER_NAME_E;